services:
  caddy:
    image: caddy:2.9.1
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./caddy:/bin/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
